version: "3"

services:
  mypython:
    build: ./
    tty: true
    environment:
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    entrypoint: streamlit run /tmp/main.py --server.port=${PORT} --server.address=0.0.0.0
